import React, { useState } from 'react';
import { ShieldCheck, ShieldAlert, AlertTriangle, HelpCircle, Copy, Check, Calendar, Info } from 'lucide-react';
import { RiskAssessment } from '../types/index';

interface RiskScoreCardProps {
  risk: RiskAssessment;
  maskedPhone: string;
  queryTimestamp: string;
  isMockData?: boolean;
}

export const RiskScoreCard: React.FC<RiskScoreCardProps> = ({
  risk,
  maskedPhone,
  queryTimestamp,
  isMockData,
}) => {
  const [copied, setCopied] = useState(false);

  const formattedDate = new Date(queryTimestamp).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const handleCopySummary = () => {
    const text = `FraudCheck BD Report\nPhone: ${maskedPhone}\nDelivery Risk Score: ${risk.score}/100 (${risk.level})\nVerdict: ${risk.verdictTitle}\nSummary: ${risk.summary}\nChecked: ${formattedDate}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Color mappings per risk level
  const getBadgeStyle = () => {
    switch (risk.level) {
      case 'LOW RISK':
        return {
          cardBorder: 'border-emerald-200/90',
          scoreColor: 'text-emerald-700',
          badgeBg: 'bg-emerald-50 text-emerald-800 border-emerald-200',
          icon: <ShieldCheck className="w-6 h-6 text-emerald-600" />,
          progressBg: 'bg-emerald-500',
        };
      case 'MEDIUM RISK':
        return {
          cardBorder: 'border-amber-200/90',
          scoreColor: 'text-amber-700',
          badgeBg: 'bg-amber-50 text-amber-800 border-amber-200',
          icon: <AlertTriangle className="w-6 h-6 text-amber-600" />,
          progressBg: 'bg-amber-500',
        };
      case 'HIGH RISK':
        return {
          cardBorder: 'border-rose-200/90',
          scoreColor: 'text-rose-700',
          badgeBg: 'bg-rose-50 text-rose-800 border-rose-200',
          icon: <ShieldAlert className="w-6 h-6 text-rose-600" />,
          progressBg: 'bg-rose-500',
        };
      default:
        return {
          cardBorder: 'border-slate-200',
          scoreColor: 'text-slate-700',
          badgeBg: 'bg-slate-100 text-slate-800 border-slate-200',
          icon: <HelpCircle className="w-6 h-6 text-slate-500" />,
          progressBg: 'bg-slate-500',
        };
    }
  };

  const styling = getBadgeStyle();

  return (
    <div
      id="customer-risk-report"
      className={`rounded-2xl bg-white p-6 sm:p-8 border ${styling.cardBorder} shadow-sm transition-all`}
    >
      {/* Report Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-5 border-b border-slate-100">
        <div>
          <span className="text-xs font-semibold uppercase tracking-wider text-slate-500">
            Customer Risk Report
          </span>
          <div className="flex items-center gap-2.5 mt-0.5">
            <span className="text-xl font-bold font-mono text-slate-900 tracking-tight" id="report-masked-phone">
              {maskedPhone}
            </span>
            <span className="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-medium bg-slate-100 text-slate-700 border border-slate-200">
              Bangladesh
            </span>
            {isMockData && (
              <span className="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-medium bg-indigo-50 text-indigo-700 border border-indigo-200" title="Generated by isolated sandbox mode because BDCOURIER_API_KEY is not yet supplied in env">
                Sandbox Profile
              </span>
            )}
          </div>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-500 flex items-center gap-1">
            <Calendar className="w-3.5 h-3.5 text-slate-400" />
            {formattedDate}
          </span>
          <button
            onClick={handleCopySummary}
            className="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium rounded-lg text-slate-600 hover:text-slate-900 hover:bg-slate-100 border border-slate-200 transition-colors cursor-pointer"
            title="Copy report summary"
            id="copy-report-btn"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-600" />
                <span className="text-emerald-700">Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-slate-400" />
                <span>Copy</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Main Score Block */}
      <div className="pt-6 grid grid-cols-1 md:grid-cols-12 gap-6 items-center">
        {/* Big Score Visual */}
        <div className="md:col-span-5 flex flex-col items-center md:items-start text-center md:text-left">
          <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">
            Delivery Risk
          </span>

          <div className="flex items-baseline gap-2 mb-2">
            <span className={`text-5xl sm:text-6xl font-black font-display tracking-tight ${styling.scoreColor}`} id="score-value">
              {risk.score}
            </span>
            <span className="text-xl font-semibold text-slate-400">/ 100</span>
          </div>

          <div className="flex items-center gap-2">
            <span
              id="risk-level-badge"
              className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide border ${styling.badgeBg}`}
            >
              {styling.icon}
              <span>{risk.level}</span>
            </span>

            <span className="text-[11px] font-medium text-slate-500">
              Confidence: <strong className="text-slate-700">{risk.confidence}</strong>
            </span>
          </div>
        </div>

        {/* Verdict and Summary */}
        <div className="md:col-span-7 bg-slate-50/70 p-4 sm:p-5 rounded-xl border border-slate-200/80">
          <h4 className="text-base font-bold text-slate-900 font-display mb-1 flex items-center gap-2">
            {risk.verdictTitle}
          </h4>
          <p className="text-sm text-slate-600 leading-relaxed">
            {risk.summary}
          </p>
        </div>
      </div>

      {/* Transparent Disclaimer Notice */}
      <div className="mt-6 pt-4 border-t border-slate-100 flex items-start gap-2 text-xs text-slate-500">
        <Info className="w-4 h-4 text-slate-400 shrink-0 mt-0.5" />
        <p className="italic">
          {risk.disclaimer}
        </p>
      </div>
    </div>
  );
};
